// <auto-generated />
using System;
using Digix.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Digix.Data.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20231121214427_AddAnalysis")]
    partial class AddAnalysis
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Digix.Domain.Entities.AnalysisRules", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FamilyAnalysisId")
                        .HasColumnType("integer");

                    b.Property<bool>("FirstRule")
                        .HasColumnType("boolean");

                    b.Property<bool>("FourthRule")
                        .HasColumnType("boolean");

                    b.Property<bool>("SecondRule")
                        .HasColumnType("boolean");

                    b.Property<bool>("ThirdRule")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("FamilyAnalysisId")
                        .IsUnique();

                    b.ToTable("AnalysisRules");
                });

            modelBuilder.Entity("Digix.Domain.Entities.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Families");
                });

            modelBuilder.Entity("Digix.Domain.Entities.FamilyAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FamilyId")
                        .IsUnique();

                    b.ToTable("FamilyAnalyses");
                });

            modelBuilder.Entity("Digix.Domain.Entities.Person", b =>
                {
                    b.Property<string>("Cpf")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("FamilyId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Income")
                        .HasColumnType("numeric");

                    b.Property<bool>("IsSpouse")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Cpf");

                    b.HasIndex("FamilyId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Digix.Domain.Entities.AnalysisRules", b =>
                {
                    b.HasOne("Digix.Domain.Entities.FamilyAnalysis", "FamilyAnalysis")
                        .WithOne("Analysis")
                        .HasForeignKey("Digix.Domain.Entities.AnalysisRules", "FamilyAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FamilyAnalysis");
                });

            modelBuilder.Entity("Digix.Domain.Entities.FamilyAnalysis", b =>
                {
                    b.HasOne("Digix.Domain.Entities.Family", "Family")
                        .WithOne("FamilyAnalysis")
                        .HasForeignKey("Digix.Domain.Entities.FamilyAnalysis", "FamilyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Digix.Domain.Entities.Person", b =>
                {
                    b.HasOne("Digix.Domain.Entities.Family", "Family")
                        .WithMany("FamilyMembers")
                        .HasForeignKey("FamilyId");

                    b.Navigation("Family");
                });

            modelBuilder.Entity("Digix.Domain.Entities.Family", b =>
                {
                    b.Navigation("FamilyAnalysis");

                    b.Navigation("FamilyMembers");
                });

            modelBuilder.Entity("Digix.Domain.Entities.FamilyAnalysis", b =>
                {
                    b.Navigation("Analysis")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
